// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/usersearch.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Bio                  string   `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Followings           []*User  `protobuf:"bytes,7,rep,name=followings,proto3" json:"followings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_usersearch_d984ede584672611, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetFollowings() []*User {
	if m != nil {
		return m.Followings
	}
	return nil
}

type UserSearchResponse struct {
	UserList             []*User  `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearchResponse) Reset()         { *m = UserSearchResponse{} }
func (m *UserSearchResponse) String() string { return proto.CompactTextString(m) }
func (*UserSearchResponse) ProtoMessage()    {}
func (*UserSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_usersearch_d984ede584672611, []int{1}
}
func (m *UserSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchResponse.Unmarshal(m, b)
}
func (m *UserSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchResponse.Marshal(b, m, deterministic)
}
func (dst *UserSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchResponse.Merge(dst, src)
}
func (m *UserSearchResponse) XXX_Size() int {
	return xxx_messageInfo_UserSearchResponse.Size(m)
}
func (m *UserSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchResponse proto.InternalMessageInfo

func (m *UserSearchResponse) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UserSearchRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearchRequest) Reset()         { *m = UserSearchRequest{} }
func (m *UserSearchRequest) String() string { return proto.CompactTextString(m) }
func (*UserSearchRequest) ProtoMessage()    {}
func (*UserSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usersearch_d984ede584672611, []int{2}
}
func (m *UserSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchRequest.Unmarshal(m, b)
}
func (m *UserSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchRequest.Marshal(b, m, deterministic)
}
func (dst *UserSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchRequest.Merge(dst, src)
}
func (m *UserSearchRequest) XXX_Size() int {
	return xxx_messageInfo_UserSearchRequest.Size(m)
}
func (m *UserSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchRequest proto.InternalMessageInfo

func (m *UserSearchRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserSearchResponse)(nil), "proto.UserSearchResponse")
	proto.RegisterType((*UserSearchRequest)(nil), "proto.UserSearchRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSearchServiceClient is the client API for UserSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSearchServiceClient interface {
	GetAllUsersLikeUsername(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserSearchResponse, error)
	GetUserWithUsername(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*User, error)
}

type userSearchServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserSearchServiceClient(cc *grpc.ClientConn) UserSearchServiceClient {
	return &userSearchServiceClient{cc}
}

func (c *userSearchServiceClient) GetAllUsersLikeUsername(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserSearchResponse, error) {
	out := new(UserSearchResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/GetAllUsersLikeUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSearchServiceClient) GetUserWithUsername(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/GetUserWithUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSearchServiceServer is the server API for UserSearchService service.
type UserSearchServiceServer interface {
	GetAllUsersLikeUsername(context.Context, *UserSearchRequest) (*UserSearchResponse, error)
	GetUserWithUsername(context.Context, *UserSearchRequest) (*User, error)
}

func RegisterUserSearchServiceServer(s *grpc.Server, srv UserSearchServiceServer) {
	s.RegisterService(&_UserSearchService_serviceDesc, srv)
}

func _UserSearchService_GetAllUsersLikeUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).GetAllUsersLikeUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/GetAllUsersLikeUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).GetAllUsersLikeUsername(ctx, req.(*UserSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSearchService_GetUserWithUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).GetUserWithUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/GetUserWithUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).GetUserWithUsername(ctx, req.(*UserSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserSearchService",
	HandlerType: (*UserSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUsersLikeUsername",
			Handler:    _UserSearchService_GetAllUsersLikeUsername_Handler,
		},
		{
			MethodName: "GetUserWithUsername",
			Handler:    _UserSearchService_GetUserWithUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/usersearch.proto",
}

func init() {
	proto.RegisterFile("api/proto/usersearch.proto", fileDescriptor_usersearch_d984ede584672611)
}

var fileDescriptor_usersearch_d984ede584672611 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0x89, 0xad, 0x7f, 0x76, 0x7a, 0xd1, 0x78, 0x30, 0x56, 0x84, 0xb2, 0xa7, 0x05, 0xa1,
	0x95, 0x7a, 0x15, 0xc1, 0x53, 0x2f, 0xa5, 0x87, 0x2d, 0xc5, 0x63, 0x49, 0xcb, 0x68, 0x83, 0xe9,
	0x66, 0xcd, 0x64, 0xeb, 0xdb, 0x08, 0xbe, 0xa9, 0x4c, 0xb6, 0x87, 0x88, 0x22, 0x9e, 0x32, 0x7c,
	0x5f, 0x66, 0xe6, 0x37, 0xd0, 0xd7, 0xb5, 0x19, 0xd5, 0xde, 0x05, 0x37, 0x6a, 0x08, 0x3d, 0xa1,
	0xf6, 0xeb, 0xcd, 0x30, 0x02, 0x79, 0x18, 0x9f, 0xfc, 0x43, 0x40, 0x77, 0x41, 0xe8, 0xe5, 0x15,
	0x64, 0xfc, 0x67, 0x59, 0xe9, 0x2d, 0x2a, 0x31, 0x10, 0x45, 0x56, 0x9e, 0x30, 0x98, 0xe9, 0x2d,
	0xb2, 0xf4, 0xa8, 0x6d, 0x2b, 0x0f, 0x5a, 0xc9, 0x20, 0xca, 0x53, 0xe8, 0xac, 0x8c, 0x53, 0x9d,
	0x88, 0xb9, 0x94, 0xd7, 0x00, 0x7a, 0xa7, 0x83, 0xf6, 0xcb, 0xc6, 0x5b, 0xd5, 0x8d, 0x22, 0x6b,
	0xc9, 0xc2, 0x5b, 0x79, 0x03, 0xf0, 0xec, 0xac, 0x75, 0xef, 0xa6, 0x7a, 0x21, 0x75, 0x3c, 0xe8,
	0x14, 0xbd, 0x71, 0xaf, 0x8d, 0x35, 0xe4, 0x2c, 0x65, 0xa2, 0xf3, 0x07, 0x90, 0xcc, 0xe6, 0x31,
	0x7b, 0x89, 0x54, 0xbb, 0x8a, 0x50, 0x16, 0xfb, 0xb4, 0xd6, 0x50, 0x50, 0xe2, 0xe7, 0x84, 0x18,
	0x7d, 0x6a, 0x28, 0xe4, 0xb7, 0x70, 0x96, 0xf6, 0xbf, 0x35, 0x48, 0xe1, 0xcf, 0x63, 0xc7, 0x9f,
	0x22, 0x6d, 0x99, 0xa3, 0xdf, 0x99, 0x35, 0xca, 0x19, 0x5c, 0x4c, 0x30, 0x3c, 0x5a, 0xcb, 0x8a,
	0xa6, 0xe6, 0x15, 0xb9, 0xe0, 0x01, 0x52, 0x25, 0x9b, 0xbf, 0xed, 0xe9, 0x5f, 0xfe, 0x62, 0xf6,
	0x17, 0xdc, 0xc3, 0xf9, 0x04, 0x03, 0x8b, 0x27, 0x13, 0x36, 0xff, 0x98, 0x95, 0xde, 0xb7, 0x3a,
	0x8a, 0xf5, 0xdd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x65, 0x66, 0x62, 0xe2, 0x01, 0x00,
	0x00,
}
