// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/usersearch.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Bio                  string   `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	FollowingsCount      uint64   `protobuf:"varint,5,opt,name=followings_count,json=followingsCount,proto3" json:"followings_count,omitempty"`
	FollowersCount       uint64   `protobuf:"varint,6,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3e492f4c56b0ffa, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetFollowingsCount() uint64 {
	if m != nil {
		return m.FollowingsCount
	}
	return 0
}

func (m *User) GetFollowersCount() uint64 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

type UserSearchResponse struct {
	UserList             []*User  `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearchResponse) Reset()         { *m = UserSearchResponse{} }
func (m *UserSearchResponse) String() string { return proto.CompactTextString(m) }
func (*UserSearchResponse) ProtoMessage()    {}
func (*UserSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3e492f4c56b0ffa, []int{1}
}

func (m *UserSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchResponse.Unmarshal(m, b)
}
func (m *UserSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchResponse.Marshal(b, m, deterministic)
}
func (m *UserSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchResponse.Merge(m, src)
}
func (m *UserSearchResponse) XXX_Size() int {
	return xxx_messageInfo_UserSearchResponse.Size(m)
}
func (m *UserSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchResponse proto.InternalMessageInfo

func (m *UserSearchResponse) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UserSearchQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearchQuery) Reset()         { *m = UserSearchQuery{} }
func (m *UserSearchQuery) String() string { return proto.CompactTextString(m) }
func (*UserSearchQuery) ProtoMessage()    {}
func (*UserSearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3e492f4c56b0ffa, []int{2}
}

func (m *UserSearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchQuery.Unmarshal(m, b)
}
func (m *UserSearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchQuery.Marshal(b, m, deterministic)
}
func (m *UserSearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchQuery.Merge(m, src)
}
func (m *UserSearchQuery) XXX_Size() int {
	return xxx_messageInfo_UserSearchQuery.Size(m)
}
func (m *UserSearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchQuery proto.InternalMessageInfo

func (m *UserSearchQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserSearchResponse)(nil), "proto.UserSearchResponse")
	proto.RegisterType((*UserSearchQuery)(nil), "proto.UserSearchQuery")
}

func init() { proto.RegisterFile("proto/usersearch.proto", fileDescriptor_b3e492f4c56b0ffa) }

var fileDescriptor_b3e492f4c56b0ffa = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xc9, 0x97, 0xa4, 0x7c, 0x99, 0x82, 0xad, 0x8b, 0x94, 0xa8, 0x08, 0x21, 0x97, 0xc6,
	0x4b, 0x85, 0x7a, 0xd7, 0x83, 0x57, 0x11, 0x4c, 0xed, 0x39, 0x6c, 0xc3, 0xa8, 0x81, 0x6d, 0xb6,
	0xce, 0x6e, 0x2a, 0xfe, 0x40, 0xff, 0x97, 0xec, 0x6c, 0x6a, 0x0a, 0x9e, 0x32, 0x79, 0xde, 0x27,
	0xd9, 0x7d, 0x07, 0x66, 0x3b, 0xd2, 0x56, 0xdf, 0x74, 0x06, 0xc9, 0xa0, 0xa4, 0xfa, 0x7d, 0xc1,
	0x40, 0xc4, 0xfc, 0xc8, 0xbf, 0x03, 0x88, 0xd6, 0x06, 0x49, 0x5c, 0x42, 0xe2, 0x9c, 0xaa, 0x95,
	0x5b, 0x4c, 0x83, 0x2c, 0x28, 0x92, 0xf2, 0xbf, 0x03, 0x4f, 0x72, 0x8b, 0x2e, 0x24, 0x94, 0xca,
	0x87, 0xff, 0x7c, 0xe8, 0x00, 0x87, 0x53, 0x08, 0x37, 0x8d, 0x4e, 0x43, 0xc6, 0x6e, 0x14, 0x57,
	0x00, 0x72, 0x2f, 0xad, 0xa4, 0xaa, 0x23, 0x95, 0x46, 0x1c, 0x24, 0x9e, 0xac, 0x49, 0x89, 0x6b,
	0x98, 0xbe, 0x6a, 0xa5, 0xf4, 0x67, 0xd3, 0xbe, 0x99, 0xaa, 0xd6, 0x5d, 0x6b, 0xd3, 0x38, 0x0b,
	0x8a, 0xa8, 0x9c, 0x0c, 0xfc, 0xc1, 0x61, 0x31, 0x87, 0x1e, 0x21, 0x1d, 0xcc, 0x11, 0x9b, 0x27,
	0xbf, 0x98, 0xc5, 0xfc, 0x0e, 0x84, 0xab, 0xb1, 0xe2, 0x8a, 0x25, 0x9a, 0x9d, 0x6e, 0x0d, 0x8a,
	0xa2, 0x2f, 0xa5, 0x1a, 0x63, 0xd3, 0x20, 0x0b, 0x8b, 0xf1, 0x72, 0xec, 0xfb, 0x2f, 0x9c, 0xed,
	0x1b, 0x3e, 0x36, 0xc6, 0xe6, 0x73, 0x98, 0x0c, 0xdf, 0x3f, 0x77, 0x48, 0x5f, 0xe2, 0x0c, 0xe2,
	0x0f, 0x37, 0xf4, 0xdb, 0xf0, 0x2f, 0xcb, 0x17, 0x38, 0x1d, 0xc4, 0x15, 0xd2, 0xbe, 0xa9, 0x51,
	0xdc, 0x03, 0x78, 0xc0, 0xab, 0x9c, 0x1d, 0x1d, 0x71, 0xf4, 0xc3, 0x8b, 0xf3, 0x3f, 0xfc, 0x70,
	0xd1, 0xcd, 0x88, 0x93, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x3a, 0x24, 0x38, 0xae,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSearchServiceClient is the client API for UserSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSearchServiceClient interface {
	SearchUser(ctx context.Context, in *UserSearchQuery, opts ...grpc.CallOption) (*UserSearchResponse, error)
}

type userSearchServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserSearchServiceClient(cc *grpc.ClientConn) UserSearchServiceClient {
	return &userSearchServiceClient{cc}
}

func (c *userSearchServiceClient) SearchUser(ctx context.Context, in *UserSearchQuery, opts ...grpc.CallOption) (*UserSearchResponse, error) {
	out := new(UserSearchResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/SearchUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSearchServiceServer is the server API for UserSearchService service.
type UserSearchServiceServer interface {
	SearchUser(context.Context, *UserSearchQuery) (*UserSearchResponse, error)
}

// UnimplementedUserSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserSearchServiceServer struct {
}

func (*UnimplementedUserSearchServiceServer) SearchUser(ctx context.Context, req *UserSearchQuery) (*UserSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUser not implemented")
}

func RegisterUserSearchServiceServer(s *grpc.Server, srv UserSearchServiceServer) {
	s.RegisterService(&_UserSearchService_serviceDesc, srv)
}

func _UserSearchService_SearchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).SearchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/SearchUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).SearchUser(ctx, req.(*UserSearchQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserSearchService",
	HandlerType: (*UserSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchUser",
			Handler:    _UserSearchService_SearchUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/usersearch.proto",
}
