# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recognizer_pb2 as recognizer__pb2


class FaceRecognizerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RecognizeFaces = channel.unary_unary(
        '/proto.FaceRecognizer/RecognizeFaces',
        request_serializer=recognizer__pb2.RecognizeRequest.SerializeToString,
        response_deserializer=recognizer__pb2.RegognizeResponse.FromString,
        )


class FaceRecognizerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RecognizeFaces(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaceRecognizerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RecognizeFaces': grpc.unary_unary_rpc_method_handler(
          servicer.RecognizeFaces,
          request_deserializer=recognizer__pb2.RecognizeRequest.FromString,
          response_serializer=recognizer__pb2.RegognizeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.FaceRecognizer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
