// Code generated by protoc-gen-go. DO NOT EDIT.
// source: renewingAddress.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RenewedElasticResult struct {
	IsRenewed            bool     `protobuf:"varint,1,opt,name=isRenewed,proto3" json:"isRenewed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewedElasticResult) Reset()         { *m = RenewedElasticResult{} }
func (m *RenewedElasticResult) String() string { return proto.CompactTextString(m) }
func (*RenewedElasticResult) ProtoMessage()    {}
func (*RenewedElasticResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c265b1376e8420, []int{0}
}

func (m *RenewedElasticResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewedElasticResult.Unmarshal(m, b)
}
func (m *RenewedElasticResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewedElasticResult.Marshal(b, m, deterministic)
}
func (m *RenewedElasticResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewedElasticResult.Merge(m, src)
}
func (m *RenewedElasticResult) XXX_Size() int {
	return xxx_messageInfo_RenewedElasticResult.Size(m)
}
func (m *RenewedElasticResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewedElasticResult.DiscardUnknown(m)
}

var xxx_messageInfo_RenewedElasticResult proto.InternalMessageInfo

func (m *RenewedElasticResult) GetIsRenewed() bool {
	if m != nil {
		return m.IsRenewed
	}
	return false
}

type RenewingElasticIp struct {
	InstanceId           string   `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Node                 string   `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Pod                  string   `protobuf:"bytes,3,opt,name=pod,proto3" json:"pod,omitempty"`
	PodIp                string   `protobuf:"bytes,4,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewingElasticIp) Reset()         { *m = RenewingElasticIp{} }
func (m *RenewingElasticIp) String() string { return proto.CompactTextString(m) }
func (*RenewingElasticIp) ProtoMessage()    {}
func (*RenewingElasticIp) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c265b1376e8420, []int{1}
}

func (m *RenewingElasticIp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewingElasticIp.Unmarshal(m, b)
}
func (m *RenewingElasticIp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewingElasticIp.Marshal(b, m, deterministic)
}
func (m *RenewingElasticIp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewingElasticIp.Merge(m, src)
}
func (m *RenewingElasticIp) XXX_Size() int {
	return xxx_messageInfo_RenewingElasticIp.Size(m)
}
func (m *RenewingElasticIp) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewingElasticIp.DiscardUnknown(m)
}

var xxx_messageInfo_RenewingElasticIp proto.InternalMessageInfo

func (m *RenewingElasticIp) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *RenewingElasticIp) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *RenewingElasticIp) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *RenewingElasticIp) GetPodIp() string {
	if m != nil {
		return m.PodIp
	}
	return ""
}

func init() {
	proto.RegisterType((*RenewedElasticResult)(nil), "proto.renewedElasticResult")
	proto.RegisterType((*RenewingElasticIp)(nil), "proto.RenewingElasticIp")
}

func init() { proto.RegisterFile("renewingAddress.proto", fileDescriptor_55c265b1376e8420) }

var fileDescriptor_55c265b1376e8420 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x3f, 0x4b, 0xc6, 0x30,
	0x10, 0xc6, 0x7d, 0xed, 0x1f, 0xec, 0x0d, 0xa2, 0x87, 0x85, 0xa0, 0x22, 0xd2, 0xc9, 0xa9, 0x83,
	0xfa, 0x05, 0x1c, 0x44, 0xb2, 0x66, 0x71, 0x94, 0xda, 0x3b, 0x24, 0x50, 0x92, 0xa3, 0x49, 0xf1,
	0xeb, 0x8b, 0xd7, 0x42, 0x05, 0xdf, 0x29, 0xc7, 0xef, 0xc7, 0xe5, 0x9e, 0x07, 0xda, 0x99, 0x03,
	0x7f, 0xfb, 0xf0, 0xf5, 0x42, 0x34, 0x73, 0x4a, 0xbd, 0xcc, 0x31, 0x47, 0xac, 0xf4, 0xe9, 0x9e,
	0xe1, 0x4a, 0x3d, 0xd3, 0xeb, 0x34, 0xa4, 0xec, 0x47, 0xc7, 0x69, 0x99, 0x32, 0xde, 0x42, 0xe3,
	0x93, 0x5b, 0x8d, 0x39, 0xdc, 0x1f, 0x1e, 0xce, 0xdc, 0x0e, 0x3a, 0x81, 0x4b, 0xb7, 0xfd, 0xba,
	0xad, 0x59, 0xc1, 0x3b, 0x00, 0x1f, 0x52, 0x1e, 0xc2, 0xc8, 0x76, 0xdd, 0x69, 0xdc, 0x1f, 0x82,
	0x08, 0x65, 0x88, 0xc4, 0xe6, 0x54, 0x8d, 0xce, 0x78, 0x01, 0x85, 0x44, 0x32, 0x85, 0xa2, 0xdf,
	0x11, 0x5b, 0xa8, 0x25, 0xd2, 0x87, 0x17, 0x53, 0x2a, 0xac, 0x24, 0x92, 0x95, 0xc7, 0x77, 0x00,
	0x17, 0x97, 0xcc, 0x6f, 0x8b, 0x27, 0x46, 0x0b, 0xe7, 0x9a, 0x7a, 0x3f, 0x6e, 0xd6, 0x5a, 0xfd,
	0xbf, 0x58, 0xd7, 0x37, 0x9b, 0x39, 0x56, 0xb3, 0x3b, 0xf9, 0xac, 0xd5, 0x3e, 0xfd, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x41, 0x4d, 0xe9, 0xd8, 0x27, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteGuideClient is the client API for RouteGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteGuideClient interface {
	RenewElasticIp(ctx context.Context, in *RenewingElasticIp, opts ...grpc.CallOption) (*RenewedElasticResult, error)
}

type routeGuideClient struct {
	cc *grpc.ClientConn
}

func NewRouteGuideClient(cc *grpc.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) RenewElasticIp(ctx context.Context, in *RenewingElasticIp, opts ...grpc.CallOption) (*RenewedElasticResult, error) {
	out := new(RenewedElasticResult)
	err := c.cc.Invoke(ctx, "/proto.RouteGuide/renewElasticIp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteGuideServer is the server API for RouteGuide service.
type RouteGuideServer interface {
	RenewElasticIp(context.Context, *RenewingElasticIp) (*RenewedElasticResult, error)
}

// UnimplementedRouteGuideServer can be embedded to have forward compatible implementations.
type UnimplementedRouteGuideServer struct {
}

func (*UnimplementedRouteGuideServer) RenewElasticIp(ctx context.Context, req *RenewingElasticIp) (*RenewedElasticResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewElasticIp not implemented")
}

func RegisterRouteGuideServer(s *grpc.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_RenewElasticIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewingElasticIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).RenewElasticIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RouteGuide/RenewElasticIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).RenewElasticIp(ctx, req.(*RenewingElasticIp))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "renewElasticIp",
			Handler:    _RouteGuide_RenewElasticIp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "renewingAddress.proto",
}
