version: '3.6'


services:
  elasticsearch_node1:
    image: elasticsearch:7.4.1
    container_name: es01
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: kibana:7.4.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_node1:9200"]

volumes:
  data01:
    driver: local
